apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes
  namespace: default
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
      - name: notes
        image: ghcr.io/notify-fhict/microservices/notes:main
        ports:
        - containerPort: 3000
          name: rest
          protocol: TCP
      imagePullSecrets:
        - name: ghcr-login-secret
