apiVersion: v1
kind: Service
metadata:
  name: push-notification
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000  
    name: rest
    protocol: TCP
  selector:
    app: push-notification
