apiVersion: apps/v1
kind: Deployment
metadata:
  name: tags
  namespace: i442651
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  selector:
    matchLabels:
      app: tags
  template:
    metadata:
      labels:
        app: tags
    spec:
      containers:
      - name: tags
        image: ghcr.io/notify-fhict/microservices/tags
        ports:
        - containerPort: 3000
          name: rest
          protocol: TCP
 