apiVersion: apps/v1
kind: Deployment
metadata:
  name: tags
  namespace: i442651
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: ghcr.io/notify-fhict/microservices/user
        ports:
        - containerPort: 3000
          name: rest
          protocol: TCP
 