apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: i442651
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: ghcr.io/notify-fhict/microservices/user:main
        ports:
        - containerPort: 3000
          name: rest
          protocol: TCP
      imagePullSecrets:
        - name: ghcr-login-secret
 