# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: GO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
    
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.2'

    - name: Build agenda
      run: go build -v ./agenda/...

    - name: Build notes
      run: go build -v ./notes/...

    - name: Test agenda
      run: go test -v ./agenda/...
    
    - name: Test notes
      run: go test -v ./notes/...
    
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        run:  docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
      
      - name: Build the Docker image
        #run: docker build -t ${{ secrets.DOCKER_USERNAME }}/micro .
        run: docker compose build 


      - name: Push to docker registry
        #run: docker push ${{ secrets.DOCKER_USERNAME }}/micro
        run: docker compose push
          #start_on_k8:
          #name: start on k8 
          #runs-on: self-hosted
          #steps:
      - name: login vsphere kubectl 
      #  run: echo "/root/K8s_setup_Yuki.sh" > /root/.signature; cat /root/.signature
        run: /root/K8s_setup_Yuki.sh
      - name: remove old dep 
      #  run: echo "kubectl delete deployment micro" > /root/.signature; cat /root/.signature
        run: kubectl delete deployment micro-notes
      - name: remove old dep 
        run: kubectl delete deployment micro-agenda

      - name: create new dep 
      #  run: echo "kubectl create deployment micro --image yukiiso/micro" > /root/.signature; cat /root/.signature
        run: kubectl create deployment micro-notes --image ${{ secrets.DOCKER_USERNAME }}/micro-notes
      - name: create new dep 
        run: kubectl create deployment micro-agenda --image ${{ secrets.DOCKER_USERNAME }}/micro-agenda
